import type { DataConfidence, SourceMeta } from '@/lib/types';
import {
  adr026DynamicFeesSource,
  adr028ExploitConciliationSource,
  appLayerSource,
  archivedSaversLendingSource as archivedSource,
  bifrostTssVaultsSource,
  assetNotationSource,
  continuousLiquidityPoolsSource as clpSource,
  constantsMimirSource,
  cosmWasmSource as cosmwasmSource,
  exploitReport2Source,
  feesSource,
  liquidityProviderFaqSource,
  liquidityProvidersSource,
  networkHaltsSource,
  protocolUpgradeV319Source,
  postRestartSecuritySource,
  queryingThorchainSource,
  runePoolDevSource,
  runePoolDocsSource,
  runePoolEndpointSource,
  securedAssetsDevSource,
  tcyGuideSource,
  thorchainDevDocsSource as devDocsSource,
  thornameGuideSource,
  thornodeBifrostHowItWorksSource,
  thornodeVaultBehaviorsSource,
  tradeAssetsSource,
  tokenomicsSource,
} from '@/lib/sources';
import { slugifyFragment } from '@/lib/utils';

export interface GlossaryTerm {
  id: string;
  term: string;
  definition: string;
  category: 'protocol' | 'economics' | 'operations' | 'history' | 'developer';
  confidence: DataConfidence;
  reviewedAt: string;
  nextReviewDue: string;
  sources: SourceMeta[];
  relatedHrefs: string[];
}

export interface GlossaryDefinitionPath {
  title: string;
  badge: 'operations' | 'economics' | 'developer' | 'history';
  description: string;
  termIds: string[];
  verifyHref: string;
  verifyLabel: string;
  boundary: string;
}

export const GLOSSARY_DEFINITION_PATHS: GlossaryDefinitionPath[] = [
  {
    title: 'Live State Terms',
    badge: 'operations',
    description: 'Use these terms when a claim depends on current THORNode, Mimir, inbound, halt, pause, or source-health state.',
    termIds: ['mimir', 'mimir-override', 'inbound-address', 'current-only'],
    verifyHref: '/network#network-diagnostics',
    verifyLabel: 'Verify in network diagnostics',
    boundary: 'A definition does not prove the network is open right now.',
  },
  {
    title: 'Vault, Signing, And Observation Terms',
    badge: 'operations',
    description: 'Use these for vault membership, chain observation, TSS, signing health, and compromised-vault wording before turning architecture terms into safety claims.',
    termIds: ['asgard-vault', 'bifrost', 'tss', 'key-sign-failures', 'compromised-vault'],
    verifyHref: '/deep-dives#deep-dive-path-network-security',
    verifyLabel: 'Follow security evidence path',
    boundary: 'Vault and signing vocabulary does not prove current signing health, vault safety, or chain observation completeness.',
  },
  {
    title: 'Swap And Fee Terms',
    badge: 'economics',
    description: 'Use these for CLP, quotes, refund boundaries, liquidity, fee, affiliate, and dynamic-fee vocabulary before quoting a number or route conclusion.',
    termIds: ['clp', 'quote', 'quote-expiry', 'recommended-min-amount-in', 'dust-threshold', 'refund-address', 'streaming-swap', 'liquidity-tolerance-bps', 'outbound-fee', 'affiliate-fee', 'thorname', 'dynamic-l1-fee'],
    verifyHref: '/deep-dives/streaming-swaps-refunds#what-to-check-first',
    verifyLabel: 'Check swap/refund evidence',
    boundary: 'Static swap and fee terms do not prove live quoteability, settlement, refund cause, route competitiveness, or revenue lift.',
  },
  {
    title: 'Liquidity And Pool Accounting Terms',
    badge: 'economics',
    description: 'Use these when an LP, liquidity-unit, impermanent-loss, RUNEPool, or POL claim needs an action, accounting, or live-source boundary.',
    termIds: ['liquidity-provider', 'liquidity-units', 'asymmetric-withdrawal', 'impermanent-loss', 'impermanent-loss-protection', 'protocol-owned-liquidity', 'runepool'],
    verifyHref: '/deep-dives/liquidity-actions#what-to-check-first',
    verifyLabel: 'Check liquidity evidence ladder',
    boundary: 'Pool accounting terms do not prove LP actions are open, yield is positive, POL scope is stable, or a pool is routeable.',
  },
  {
    title: 'App Layer And Asset Terms',
    badge: 'developer',
    description: 'Use these when explaining memos, CosmWasm, secured assets, trade assets, and app-layer availability boundaries.',
    termIds: ['memo', 'app-layer', 'cosmwasm', 'secured-asset', 'trade-asset', 'synthetic-asset'],
    verifyHref: '/deep-dives/app-layer',
    verifyLabel: 'Read app-layer explainer',
    boundary: 'Do not infer contract, secured-asset, trade-account, or archived synth availability without live controls and dated product context.',
  },
  {
    title: 'Incident And Recovery Terms',
    badge: 'history',
    description: 'Use these for deprecated THORFi context, TCY, and post-exploit TSS/security vocabulary.',
    termIds: ['savers', 'tcy', 'gg20', 'dkls', 'schnorr', 'paillier', 'mta', 'multi-prime-modulus', 'keyverify'],
    verifyHref: '/governance#current-recovery',
    verifyLabel: 'Check recovery tracker',
    boundary: 'Dated incident vocabulary is not present-day safety or recovery proof.',
  },
];

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    id: slugifyFragment('Asgard vault'),
    term: 'Asgard vault',
    definition: 'A THORChain vault controlled by the active validator set through threshold signing. Vault membership changes during churns.',
    category: 'protocol',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [bifrostTssVaultsSource, thornodeVaultBehaviorsSource],
    relatedHrefs: ['/deep-dives/tss', '/deep-dives/churning'],
  },
  {
    id: slugifyFragment('Bifrost'),
    term: 'Bifrost',
    definition: 'The chain-client layer active nodes use to observe external-chain transactions and submit observations into THORChain.',
    category: 'protocol',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [bifrostTssVaultsSource, thornodeBifrostHowItWorksSource],
    relatedHrefs: ['/deep-dives/bifrost'],
  },
  {
    id: slugifyFragment('CLP'),
    term: 'CLP',
    definition: 'Continuous Liquidity Pool. THORChain pools price swaps from pool depth and slip, with RUNE paired against external assets.',
    category: 'economics',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [clpSource],
    relatedHrefs: ['/deep-dives/clp', '/economics'],
  },
  {
    id: slugifyFragment('Impermanent loss'),
    term: 'Impermanent loss',
    definition: 'Liquidity-provider purchasing-power risk when relative pool asset prices move. THORChain docs frame slip-based fees as reducing this risk, not removing it; current LP return claims still need live pool and earnings evidence.',
    category: 'economics',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [liquidityProvidersSource, clpSource],
    relatedHrefs: ['/deep-dives/clp', '/stats#stats-look-here-first'],
  },
  {
    id: slugifyFragment('Impermanent loss protection'),
    term: 'Impermanent loss protection',
    definition: 'A historical reserve-subsidy mechanism for LP withdrawals. Official THORChain docs now say IL protection has been removed or ended, so do not describe it as currently available for ordinary liquidity providers.',
    category: 'history',
    confidence: 'official',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [clpSource, liquidityProvidersSource],
    relatedHrefs: ['/deep-dives/clp', '/docs#historical-features-and-recovery'],
  },
  {
    id: slugifyFragment('Liquidity provider'),
    term: 'Liquidity provider',
    definition: 'A participant who supplies assets to a THORChain pool and receives pool-share accounting plus a share of pool earnings and final balances. Current deposit or withdrawal availability depends on live LP controls, lockup rules, outbound state, and chain state.',
    category: 'economics',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [liquidityProvidersSource, networkHaltsSource],
    relatedHrefs: ['/deep-dives/clp', '/network#network-diagnostics'],
  },
  {
    id: slugifyFragment('Liquidity units'),
    term: 'Liquidity units',
    definition: 'Accounting units used to track a provider share of a THORChain pool. Units explain proportional pool ownership and redemption accounting, not whether LP deposits or withdrawals are currently open or what a position will return.',
    category: 'economics',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [liquidityProviderFaqSource, devDocsSource],
    relatedHrefs: ['/deep-dives/clp', '/stats#stats-look-here-first'],
  },
  {
    id: slugifyFragment('Asymmetric withdrawal'),
    term: 'Asymmetric withdrawal',
    definition: 'A liquidity withdrawal that takes one side of a pool rather than both sides proportionally. Availability can be controlled separately by live Mimir pause keys.',
    category: 'operations',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [liquidityProviderFaqSource, networkHaltsSource],
    relatedHrefs: ['/network#network-diagnostics', '/deep-dives/clp'],
  },
  {
    id: slugifyFragment('Current-only'),
    term: 'Current-only',
    definition: 'A trust label for live Midgard or THORNode data that should be treated as a fresh snapshot, not durable historical truth.',
    category: 'operations',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [queryingThorchainSource],
    relatedHrefs: ['/stats', '/network'],
  },
  {
    id: slugifyFragment('Mimir'),
    term: 'Mimir',
    definition: 'Operational parameter storage used by THORChain nodes. Halt, pause, enablement, and feature-control keys must be read from live THORNode state.',
    category: 'operations',
    confidence: 'official',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [networkHaltsSource],
    relatedHrefs: ['/network', '/deep-dives/mimir-halt-controls', '/governance'],
  },
  {
    id: slugifyFragment('Mimir override'),
    term: 'Mimir override',
    definition: 'A live operational value that can override a protocol default or constant. Current behavior should be checked against both constants and Mimir.',
    category: 'operations',
    confidence: 'official',
    reviewedAt: '2026-07-05',
    nextReviewDue: '2026-08-05',
    sources: [networkHaltsSource, queryingThorchainSource],
    relatedHrefs: ['/protocol', '/network#network-diagnostics'],
  },
  {
    id: slugifyFragment('Inbound address'),
    term: 'Inbound address',
    definition: 'A current THORNode-provided address, router, gas-rate, and pause-state record for a supported external chain. Treat it as live availability evidence only.',
    category: 'operations',
    confidence: 'official',
    reviewedAt: '2026-07-05',
    nextReviewDue: '2026-08-05',
    sources: [queryingThorchainSource, devDocsSource],
    relatedHrefs: ['/protocol', '/docs#current-protocol-state'],
  },
  {
    id: slugifyFragment('Memo'),
    term: 'Memo',
    definition: 'The transaction instruction string used by THORChain actions such as swaps, LP operations, refunds, affiliates, and other protocol messages.',
    category: 'developer',
    confidence: 'curated',
    reviewedAt: '2026-07-05',
    nextReviewDue: '2026-08-05',
    sources: [devDocsSource, queryingThorchainSource],
    relatedHrefs: ['/protocol', '/docs#developer-integration'],
  },
  {
    id: slugifyFragment('Quote'),
    term: 'Quote',
    definition: 'A short-lived THORNode swap response for a specific from-asset, to-asset, and amount. It can prove the route response at the checked time, but it is not wallet instructions, settlement proof, or durable route availability.',
    category: 'operations',
    confidence: 'curated',
    reviewedAt: '2026-07-06',
    nextReviewDue: '2026-08-06',
    sources: [queryingThorchainSource, feesSource],
    relatedHrefs: ['/network#network-diagnostics', '/deep-dives/streaming-swaps-refunds#what-to-check-first'],
  },
  {
    id: slugifyFragment('Quote expiry'),
    term: 'Quote expiry',
    definition: 'The time limit after which a quote should no longer be treated as current. Expired quotes need a fresh quote before making route, fee, slippage, or minimum-input claims.',
    category: 'operations',
    confidence: 'curated',
    reviewedAt: '2026-07-06',
    nextReviewDue: '2026-08-06',
    sources: [queryingThorchainSource],
    relatedHrefs: ['/network#network-diagnostics', '/deep-dives/streaming-swaps-refunds#memos-limits-and-refund-addresses'],
  },
  {
    id: slugifyFragment('recommended_min_amount_in'),
    term: 'recommended_min_amount_in',
    definition: 'A quote-field signal for the recommended minimum input amount, using THORChain base units. It is a current quote constraint, not a guarantee that a later transaction will execute or avoid refund.',
    category: 'economics',
    confidence: 'curated',
    reviewedAt: '2026-07-06',
    nextReviewDue: '2026-08-06',
    sources: [feesSource, queryingThorchainSource],
    relatedHrefs: ['/network#network-diagnostics', '/deep-dives/streaming-swaps-refunds#memos-limits-and-refund-addresses'],
  },
  {
    id: slugifyFragment('Dust threshold'),
    term: 'Dust threshold',
    definition: 'A minimum amount boundary below which a chain or route may reject, ignore, or refund an action. Treat exact thresholds as live quote, inbound-address, or chain-specific evidence.',
    category: 'operations',
    confidence: 'curated',
    reviewedAt: '2026-07-06',
    nextReviewDue: '2026-08-06',
    sources: [queryingThorchainSource, feesSource],
    relatedHrefs: ['/network#network-diagnostics', '/deep-dives/build-query-data#quotes-inbound-addresses-and-caching'],
  },
  {
    id: slugifyFragment('Refund address'),
    term: 'Refund address',
    definition: 'The address used for returning funds when a swap or action cannot complete. A glossary definition cannot prove a specific refund cause; use transaction evidence, memo shape, quote state, and live halts together.',
    category: 'operations',
    confidence: 'curated',
    reviewedAt: '2026-07-06',
    nextReviewDue: '2026-08-06',
    sources: [devDocsSource, queryingThorchainSource],
    relatedHrefs: ['/deep-dives/streaming-swaps-refunds#what-to-check-first', '/network#network-diagnostics'],
  },
  {
    id: slugifyFragment('Streaming swap'),
    term: 'Streaming swap',
    definition: 'A swap execution style that can split execution over time or intervals to reduce price impact. Current streaming support, interval, limits, and refund behavior must come from quote and transaction evidence.',
    category: 'operations',
    confidence: 'curated',
    reviewedAt: '2026-07-06',
    nextReviewDue: '2026-08-06',
    sources: [devDocsSource, feesSource],
    relatedHrefs: ['/deep-dives/streaming-swaps-refunds', '/network#network-diagnostics'],
  },
  {
    id: slugifyFragment('liquidity_tolerance_bps'),
    term: 'liquidity_tolerance_bps',
    definition: 'A basis-point tolerance used in swap or memo contexts to constrain acceptable liquidity/slippage behavior. It is not itself proof that a route is safe, cheap, or currently executable.',
    category: 'economics',
    confidence: 'curated',
    reviewedAt: '2026-07-06',
    nextReviewDue: '2026-08-06',
    sources: [devDocsSource, feesSource],
    relatedHrefs: ['/deep-dives/streaming-swaps-refunds#memos-limits-and-refund-addresses', '/deep-dives/clp#evidence-ladder'],
  },
  {
    id: slugifyFragment('Outbound fee'),
    term: 'Outbound fee',
    definition: 'A fee component associated with the outbound transaction and chain gas. Exact values are live protocol data, not static wiki constants.',
    category: 'economics',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [feesSource],
    relatedHrefs: ['/economics', '/stats#stats-look-here-first'],
  },
  {
    id: slugifyFragment('Affiliate fee'),
    term: 'Affiliate fee',
    definition: 'An optional memo-defined interface or affiliate fee, usually expressed in basis points. It is distinct from protocol liquidity and gas-related fees.',
    category: 'economics',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [feesSource],
    relatedHrefs: ['/economics', '/dynamic-fees#dynamic-fees-live'],
  },
  {
    id: slugifyFragment('THORName'),
    term: 'THORName',
    definition: 'A THORChain L1 vanity-name and alias record with an owner, expiry, chain aliases, and optional preferred asset for affiliate-fee payouts. It can support affiliate tracking and fee collection, but it does not by itself prove current dynamic-fee attribution, route quality, or interface safety.',
    category: 'developer',
    confidence: 'official',
    reviewedAt: '2026-07-09',
    nextReviewDue: '2026-08-09',
    sources: [thornameGuideSource],
    relatedHrefs: ['/docs#developer-integration', '/dynamic-fees#dynamic-fees-live', '/glossary#term-affiliate-fee'],
  },
  {
    id: slugifyFragment('Dynamic L1 fee'),
    term: 'Dynamic L1 fee',
    definition: 'ADR-026 experiment terminology for per-thorname, per-pair L1 minimum slip floors adjusted by TOR-denominated fee evidence. Live state is current-only THORNode evidence.',
    category: 'economics',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [adr026DynamicFeesSource],
    relatedHrefs: ['/dynamic-fees#dynamic-fees-live', '/docs#dynamic-fee-experiment'],
  },
  {
    id: slugifyFragment('Protocol-owned liquidity'),
    term: 'Protocol-owned liquidity',
    definition: 'Liquidity controlled by the protocol rather than ordinary external LPs. Balances and PnL come from current accounting, while enabled pool scope comes from live `POL-<Asset>` Mimir keys; neither should be inferred from a fixed documentation count.',
    category: 'economics',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [runePoolDocsSource, runePoolDevSource, runePoolEndpointSource],
    relatedHrefs: ['/economics#runepool-pol-live', '/deep-dives/runepool-pol#accounting-checks', '/stats#stats-look-here-first'],
  },
  {
    id: slugifyFragment('RUNEPool'),
    term: 'RUNEPool',
    definition: 'A RUNE-only participation mechanism with aggregate exposure to POL-enabled pools. Current value, potentially negative PnL/current-deposit fields, POL scope, and deposit or withdrawal availability need same-provider, height-pinned THORNode and Mimir evidence.',
    category: 'economics',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [runePoolDocsSource, runePoolDevSource, runePoolEndpointSource, networkHaltsSource],
    relatedHrefs: ['/economics#runepool-pol-live', '/deep-dives/runepool-pol#accounting-checks', '/network#network-diagnostics'],
  },
  {
    id: slugifyFragment('Secured asset'),
    term: 'Secured asset',
    definition: 'A Cosmos bank asset minted from deposited L1 assets, representing a share claim on the deposited-asset pool and usable by accounts, IBC, and CosmWasm. Deposits, withdrawals, and route availability depend on current controls.',
    category: 'protocol',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [securedAssetsDevSource, assetNotationSource, networkHaltsSource],
    relatedHrefs: ['/deep-dives/app-layer', '/economics', '/network#network-diagnostics'],
  },
  {
    id: slugifyFragment('Trade asset'),
    term: 'Trade asset',
    definition: 'A 1:1 L1-backed balance held outside liquidity pools in THORChain\'s trade-account module for fast trading flows. Trade assets use `CHAIN~ASSET` notation; enablement and route availability are live controls.',
    category: 'protocol',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [tradeAssetsSource, assetNotationSource, networkHaltsSource],
    relatedHrefs: ['/deep-dives/app-layer', '/economics', '/network#network-diagnostics'],
  },
  {
    id: slugifyFragment('Synthetic asset'),
    term: 'Synthetic asset',
    definition: 'A THORChain asset-notation type, often shortened to synth, denoted with `CHAIN/ASSET`. Synthetics were part of historical Savers mechanics; notation may still appear in developer contexts, but current availability or halt state must be checked from live controls and archived-product boundaries.',
    category: 'history',
    confidence: 'curated',
    reviewedAt: '2026-07-05',
    nextReviewDue: '2026-08-05',
    sources: [assetNotationSource, archivedSource, networkHaltsSource],
    relatedHrefs: ['/deep-dives/savers', '/docs#developer-integration', '/network#network-diagnostics'],
  },
  {
    id: slugifyFragment('App Layer'),
    term: 'App Layer',
    definition: 'THORChain application-layer functionality built around CosmWasm contracts, Mimir-governed deployment permissioning, and scoped deployer, checksum, and contract controls.',
    category: 'developer',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [appLayerSource, cosmwasmSource, constantsMimirSource, networkHaltsSource],
    relatedHrefs: ['/deep-dives/app-layer', '/protocol', '/network#network-diagnostics'],
  },
  {
    id: slugifyFragment('CosmWasm'),
    term: 'CosmWasm',
    definition: 'Smart-contract technology used for THORChain app-layer functionality. Current deployer, checksum, contract, or global halt state must be read from live controls.',
    category: 'developer',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [cosmwasmSource, networkHaltsSource],
    relatedHrefs: ['/deep-dives/app-layer', '/protocol', '/docs#official-protocol-documentation'],
  },
  {
    id: slugifyFragment('Savers'),
    term: 'Savers',
    definition: 'A deprecated historical THORFi feature. Current wiki copy should frame Savers as archived, not presently available yield.',
    category: 'history',
    confidence: 'official',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [archivedSource, tcyGuideSource],
    relatedHrefs: ['/tcy', '/deep-dives/savers'],
  },
  {
    id: slugifyFragment('TCY'),
    term: 'TCY',
    definition: 'A recovery-token framing associated with the THORFi unwind. Official sources describe 1 TCY per $1 of defaulted THORFi debt and warn that full recovery is market dependent, so current claim, staking, and value claims need fresh evidence.',
    category: 'history',
    confidence: 'official',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [tokenomicsSource, tcyGuideSource, archivedSource],
    relatedHrefs: ['/tcy', '/deep-dives/tcy-recovery-timeline', '/governance#current-recovery'],
  },
  {
    id: slugifyFragment('DKLS'),
    term: 'DKLS',
    definition: 'A threshold-signature scheme family in THORChain\'s post-exploit migration plan. The June 2026 post-restart update still describes chain-by-chain DKLS/FROST migration as future work, not completed current implementation.',
    category: 'history',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [exploitReport2Source, postRestartSecuritySource],
    relatedHrefs: ['/deep-dives/tss', '/governance#current-recovery'],
  },
  {
    id: slugifyFragment('Schnorr'),
    term: 'Schnorr',
    definition: 'A signature construction related to the FROST direction discussed after the GG20 exploit. Official post-restart reporting describes evaluation and future chain-by-chain migration, not proof that current vault signing has moved to Schnorr/FROST.',
    category: 'history',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [exploitReport2Source, postRestartSecuritySource],
    relatedHrefs: ['/deep-dives/tss', '/governance#current-recovery'],
  },
  {
    id: slugifyFragment('GG20'),
    term: 'GG20',
    definition: 'The threshold-signature implementation family used in the May 2026 exploit path. v3.19.1 patched the incident class, but official post-restart reporting still treats migration away from GG20 as future work; neither fact is present-day vault-safety proof.',
    category: 'history',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [exploitReport2Source, protocolUpgradeV319Source, postRestartSecuritySource],
    relatedHrefs: ['/deep-dives/tss', '/governance#current-recovery'],
  },
  {
    id: slugifyFragment('Paillier'),
    term: 'Paillier',
    definition: 'A cryptographic component used in the GG20/ECDSA signing path discussed in the 2026 exploit report. The report ties malformed Paillier key material to the attack, so Paillier claims should stay attached to dated incident sources.',
    category: 'history',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [exploitReport2Source],
    relatedHrefs: ['/deep-dives/tss', '/governance#current-recovery'],
  },
  {
    id: slugifyFragment('MTA'),
    term: 'MTA',
    definition: 'Multiplicative-to-additive signing-round terminology from GG20/ECDSA threshold signing. THORChain Exploit Report 2 says repeated failed MTA rounds leaked enough key-share material for the attacker to reproduce one vault key.',
    category: 'history',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [exploitReport2Source],
    relatedHrefs: ['/deep-dives/tss', '/governance#current-recovery'],
  },
  {
    id: slugifyFragment('Multi-prime modulus'),
    term: 'Multi-prime modulus',
    definition: 'A Paillier-key property discussed in the official exploit report. Use it as incident-root-cause vocabulary, not as a standalone explanation of current THORChain cryptography.',
    category: 'history',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [exploitReport2Source],
    relatedHrefs: ['/deep-dives/tss', '/governance#current-recovery'],
  },
  {
    id: slugifyFragment('Key-sign failures'),
    term: 'Key-sign failures',
    definition: 'Validator signing failures or failed signing rounds. Exploit Report 2 says many deliberate MTA failures looked like ordinary node flakiness in isolation, so key-sign failure claims need dated incident context and current monitoring evidence.',
    category: 'operations',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [exploitReport2Source, protocolUpgradeV319Source, postRestartSecuritySource],
    relatedHrefs: ['/deep-dives/tss', '/network#network-diagnostics', '/governance#current-recovery'],
  },
  {
    id: slugifyFragment('Compromised vault'),
    term: 'Compromised vault',
    definition: 'A vault treated as unsafe or excluded after key-compromise evidence. Post-exploit upgrade notes discuss compromised-vault exclusion, but current vault status still needs live protocol and incident-source checks.',
    category: 'operations',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [exploitReport2Source, protocolUpgradeV319Source, adr028ExploitConciliationSource],
    relatedHrefs: ['/deep-dives/tss', '/network#network-diagnostics', '/governance#current-recovery'],
  },
  {
    id: slugifyFragment('KeyVerify'),
    term: 'KeyVerify',
    definition: 'A temporary recovery check introduced around the v3.19 restart to confirm validators\' security keys before trading resumed. It is dated recovery evidence, not a standing guarantee of current vault or signing safety.',
    category: 'history',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [protocolUpgradeV319Source, exploitReport2Source],
    relatedHrefs: ['/deep-dives/tss', '/governance#current-recovery'],
  },
  {
    id: slugifyFragment('TSS'),
    term: 'TSS',
    definition: 'Threshold Signature Scheme. Validators jointly sign vault transactions without a single node intending to hold the complete private key; current scheme and safety claims require dated incident, release, and live evidence.',
    category: 'protocol',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [bifrostTssVaultsSource, exploitReport2Source, postRestartSecuritySource],
    relatedHrefs: ['/deep-dives/tss'],
  },
];
