import type { DataConfidence, SourceMeta } from '@/lib/types';
import {
  adr026DynamicFeesSource,
  adr028ExploitConciliationSource,
  appLayerSource,
  archivedLendingSource,
  archivedSaversLendingSource as archivedSource,
  archivedSaversSource,
  bifrostTssVaultsSource,
  assetNotationSource,
  continuousLiquidityPoolsSource as clpSource,
  constantsMimirSource,
  cosmWasmSource as cosmwasmSource,
  exploitReport2Source,
  feesSource,
  liquidityProviderFaqSource,
  liquidityProvidersSource,
  memosSource,
  networkHaltsSource,
  protocolUpgradeV319Source,
  postRestartSecuritySource,
  queryingThorchainSource,
  runePoolDevSource,
  runePoolDocsSource,
  runePoolEndpointSource,
  securedAssetsDevSource,
  securedAssetsSource,
  streamingSwapsSource,
  swapGuideSource,
  tcyGuideSource,
  thorchainDevDocsSource as devDocsSource,
  thornameGuideSource,
  thornodeBifrostHowItWorksSource,
  thornodeVaultBehaviorsSource,
  tradeAssetsSource,
  tokenomicsSource,
} from '@/lib/sources';
import { slugifyFragment } from '@/lib/utils';

export interface GlossaryTerm {
  id: string;
  term: string;
  definition: string;
  category: 'protocol' | 'economics' | 'operations' | 'history' | 'developer';
  confidence: DataConfidence;
  reviewedAt: string;
  nextReviewDue: string;
  sources: SourceMeta[];
  relatedHrefs: string[];
}

export interface GlossaryDefinitionPath {
  title: string;
  badge: 'operations' | 'economics' | 'developer' | 'history';
  description: string;
  termIds: string[];
  verifyHref: string;
  verifyLabel: string;
  boundary: string;
}

export const GLOSSARY_DEFINITION_PATHS: GlossaryDefinitionPath[] = [
  {
    title: 'Live State Terms',
    badge: 'operations',
    description: 'Use these terms when a claim depends on current THORNode, Mimir, inbound, halt, pause, or source-health state.',
    termIds: ['mimir', 'mimir-override', 'inbound-address', 'current-only'],
    verifyHref: '/network#network-diagnostics',
    verifyLabel: 'Verify in network diagnostics',
    boundary: 'A definition does not prove the network is open right now.',
  },
  {
    title: 'Vault, Signing, And Observation Terms',
    badge: 'operations',
    description: 'Use these for vault membership, chain observation, TSS, signing health, and compromised-vault wording before turning architecture terms into safety claims.',
    termIds: ['asgard-vault', 'bifrost', 'tss', 'key-sign-failures', 'compromised-vault'],
    verifyHref: '/deep-dives#deep-dive-path-network-security',
    verifyLabel: 'Follow security evidence path',
    boundary: 'Vault and signing vocabulary does not prove current signing health, vault safety, or chain observation completeness.',
  },
  {
    title: 'Swap And Fee Terms',
    badge: 'economics',
    description: 'Use these for CLP, quotes, refund boundaries, liquidity, fee, affiliate, and dynamic-fee vocabulary before quoting a number or route conclusion.',
    termIds: ['clp', 'quote', 'quote-expiry', 'recommended-min-amount-in', 'dust-threshold', 'refund-address', 'streaming-swap', 'liquidity-tolerance-bps', 'outbound-fee', 'affiliate-fee', 'thorname', 'dynamic-l1-fee'],
    verifyHref: '/deep-dives/streaming-swaps-refunds#what-to-check-first',
    verifyLabel: 'Check swap/refund evidence',
    boundary: 'Static swap and fee terms do not prove live quoteability, settlement, refund cause, route competitiveness, or revenue lift.',
  },
  {
    title: 'Liquidity And Pool Accounting Terms',
    badge: 'economics',
    description: 'Use these when an LP, liquidity-unit, impermanent-loss, RUNEPool, or POL claim needs an action, accounting, or live-source boundary.',
    termIds: ['liquidity-provider', 'liquidity-units', 'asymmetric-withdrawal', 'impermanent-loss', 'impermanent-loss-protection', 'protocol-owned-liquidity', 'runepool'],
    verifyHref: '/deep-dives/liquidity-actions#what-to-check-first',
    verifyLabel: 'Check liquidity evidence ladder',
    boundary: 'Pool accounting terms do not prove LP actions are open, yield is positive, POL scope is stable, or a pool is routeable.',
  },
  {
    title: 'App Layer And Asset Terms',
    badge: 'developer',
    description: 'Use these when explaining memos, CosmWasm, secured assets, trade assets, and app-layer availability boundaries.',
    termIds: ['memo', 'app-layer', 'cosmwasm', 'secured-asset', 'trade-asset', 'synthetic-asset'],
    verifyHref: '/deep-dives/app-layer',
    verifyLabel: 'Read app-layer explainer',
    boundary: 'Do not infer contract, secured-asset, trade-account, or archived synth availability without live controls and dated product context.',
  },
  {
    title: 'Incident And Recovery Terms',
    badge: 'history',
    description: 'Use these for deprecated THORFi context, TCY, and post-exploit TSS/security vocabulary.',
    termIds: ['savers', 'tcy', 'gg20', 'dkls', 'schnorr', 'paillier', 'mta', 'multi-prime-modulus', 'keyverify'],
    verifyHref: '/governance#current-recovery',
    verifyLabel: 'Check recovery tracker',
    boundary: 'Dated incident vocabulary is not present-day safety or recovery proof.',
  },
];

const swapGlossaryQueryingSource: SourceMeta = {
  ...queryingThorchainSource,
  retrievedAt: '2026-07-14',
  notes: 'Official inbound-address, router, halt, gas-rate, dust-threshold, and no-cache guidance checked for the swap glossary review.',
};

const swapGlossaryGuideSource: SourceMeta = {
  ...swapGuideSource,
  retrievedAt: '2026-07-14',
  notes: 'Official quote response, ten-minute validity, no-cache warning, price-limit, streaming, refund-address, recommended-minimum-input, and error-handling guidance.',
};

const swapGlossaryMemosSource: SourceMeta = {
  ...memosSource,
  retrievedAt: '2026-07-14',
  notes: 'Official memo format, per-chain dust thresholds, swap limits, advanced-queue interval and quantity fields, and refund-address guidance.',
};

const swapGlossaryFeesSource: SourceMeta = {
  ...feesSource,
  retrievedAt: '2026-07-14',
  notes: 'Official refund economics and recommended_min_amount_in guidance in 1e8 inbound-asset units; exact values remain current-only.',
};

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    id: slugifyFragment('Asgard vault'),
    term: 'Asgard vault',
    definition: 'A THORChain vault controlled by the active validator set through threshold signing. Vault membership changes during churns.',
    category: 'protocol',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [bifrostTssVaultsSource, thornodeVaultBehaviorsSource],
    relatedHrefs: ['/deep-dives/tss', '/deep-dives/churning'],
  },
  {
    id: slugifyFragment('Bifrost'),
    term: 'Bifrost',
    definition: 'The chain-client layer active nodes use to observe external-chain transactions and submit observations into THORChain.',
    category: 'protocol',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [bifrostTssVaultsSource, thornodeBifrostHowItWorksSource],
    relatedHrefs: ['/deep-dives/bifrost'],
  },
  {
    id: slugifyFragment('CLP'),
    term: 'CLP',
    definition: 'Continuous Liquidity Pool. THORChain pools price swaps from pool depth and slip, with RUNE paired against external assets.',
    category: 'economics',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [clpSource],
    relatedHrefs: ['/deep-dives/clp', '/economics'],
  },
  {
    id: slugifyFragment('Impermanent loss'),
    term: 'Impermanent loss',
    definition: 'Liquidity-provider purchasing-power risk when relative pool asset prices move. THORChain docs frame slip-based fees as reducing this risk, not removing it; current LP return claims still need live pool and earnings evidence.',
    category: 'economics',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [liquidityProvidersSource, clpSource],
    relatedHrefs: ['/deep-dives/clp', '/stats#stats-look-here-first'],
  },
  {
    id: slugifyFragment('Impermanent loss protection'),
    term: 'Impermanent loss protection',
    definition: 'A historical reserve-subsidy mechanism for LP withdrawals. Official THORChain docs now say IL protection has been removed or ended, so do not describe it as currently available for ordinary liquidity providers.',
    category: 'history',
    confidence: 'official',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [clpSource, liquidityProvidersSource],
    relatedHrefs: ['/deep-dives/clp', '/docs#historical-features-and-recovery'],
  },
  {
    id: slugifyFragment('Liquidity provider'),
    term: 'Liquidity provider',
    definition: 'A participant who supplies assets to a THORChain pool and receives pool-share accounting plus a share of pool earnings and final balances. Current deposit or withdrawal availability depends on live LP controls, lockup rules, outbound state, and chain state.',
    category: 'economics',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [liquidityProvidersSource, networkHaltsSource],
    relatedHrefs: ['/deep-dives/clp', '/network#network-diagnostics'],
  },
  {
    id: slugifyFragment('Liquidity units'),
    term: 'Liquidity units',
    definition: 'Accounting units used to track a provider share of a THORChain pool. Units explain proportional pool ownership and redemption accounting, not whether LP deposits or withdrawals are currently open or what a position will return.',
    category: 'economics',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [liquidityProviderFaqSource, devDocsSource],
    relatedHrefs: ['/deep-dives/clp', '/stats#stats-look-here-first'],
  },
  {
    id: slugifyFragment('Asymmetric withdrawal'),
    term: 'Asymmetric withdrawal',
    definition: 'A liquidity withdrawal that takes one side of a pool rather than both sides proportionally. Availability can be controlled separately by live Mimir pause keys.',
    category: 'operations',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [liquidityProviderFaqSource, networkHaltsSource],
    relatedHrefs: ['/network#network-diagnostics', '/deep-dives/clp'],
  },
  {
    id: slugifyFragment('Current-only'),
    term: 'Current-only',
    definition: 'A trust label for live Midgard or THORNode data that should be treated as a fresh snapshot, not durable historical truth.',
    category: 'operations',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [queryingThorchainSource],
    relatedHrefs: ['/stats', '/network'],
  },
  {
    id: slugifyFragment('Mimir'),
    term: 'Mimir',
    definition: 'Operational parameter storage used by THORChain nodes. Halt, pause, enablement, and feature-control keys must be read from live THORNode state.',
    category: 'operations',
    confidence: 'official',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [networkHaltsSource],
    relatedHrefs: ['/network', '/deep-dives/mimir-halt-controls', '/governance'],
  },
  {
    id: slugifyFragment('Mimir override'),
    term: 'Mimir override',
    definition: 'A node-governed runtime value. A Mimir may override a compiled constant or exist without a matching constant, so current behavior requires comparing the constants table with fresh live Mimir state rather than assuming every key is an override.',
    category: 'operations',
    confidence: 'official',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [constantsMimirSource, networkHaltsSource, queryingThorchainSource],
    relatedHrefs: ['/protocol', '/network#network-diagnostics'],
  },
  {
    id: slugifyFragment('Inbound address'),
    term: 'Inbound address',
    definition: 'A current THORNode record containing an active Asgard address plus chain-specific router, gas-rate, dust, and pause fields. It must not be cached or reused across churns; re-fetch it immediately before constructing a transaction, and do not treat it alone as quote, signing, outbound, or settlement proof.',
    category: 'operations',
    confidence: 'official',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [queryingThorchainSource, devDocsSource],
    relatedHrefs: ['/protocol', '/docs#current-protocol-state'],
  },
  {
    id: slugifyFragment('Memo'),
    term: 'Memo',
    definition: 'The transaction instruction string that communicates an intended THORChain action. Valid syntax, accepted size, and current action availability are separate checks: deprecated handlers can remain documented, and an invalid or unavailable action may refund rather than execute.',
    category: 'developer',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [memosSource, queryingThorchainSource],
    relatedHrefs: ['/protocol', '/docs#developer-integration'],
  },
  {
    id: slugifyFragment('Quote'),
    term: 'Quote',
    definition: 'A short-lived THORNode simulation response for a specific swap request. It returns transaction inputs and estimates such as the inbound address, memo, expected output, fees, expiry, dust threshold, and recommended minimum input; it does not sign, broadcast, or prove settlement.',
    category: 'operations',
    confidence: 'official',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [swapGlossaryGuideSource, swapGlossaryFeesSource],
    relatedHrefs: ['/network#network-diagnostics', '/deep-dives/streaming-swaps-refunds#what-to-check-first'],
  },
  {
    id: slugifyFragment('Quote expiry'),
    term: 'Quote expiry',
    definition: 'The quote response timestamp after which its inbound address, memo, estimates, and warnings must not be used. Official guidance treats quotes as valid for only ten minutes and says to request a fresh quote immediately before transaction submission.',
    category: 'operations',
    confidence: 'official',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [swapGlossaryGuideSource],
    relatedHrefs: ['/network#network-diagnostics', '/deep-dives/streaming-swaps-refunds#memos-limits-and-refund-addresses'],
  },
  {
    id: slugifyFragment('recommended_min_amount_in'),
    term: 'recommended_min_amount_in',
    definition: 'The quote field for the minimum allowed input, priced in 1e8 units of the inbound asset. It applies the documented source-fee, destination-fee, and one-dollar floor with a gas-spike buffer; it is still a current quote value, not an execution guarantee.',
    category: 'economics',
    confidence: 'official',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [swapGlossaryFeesSource, swapGlossaryGuideSource],
    relatedHrefs: ['/network#network-diagnostics', '/deep-dives/streaming-swaps-refunds#memos-limits-and-refund-addresses'],
  },
  {
    id: slugifyFragment('Dust threshold'),
    term: 'Dust threshold',
    definition: 'A per-chain minimum inbound amount required for THORChain to process a transaction; amounts below it are ignored. Treat the exact value as live chain-specific evidence from a fresh quote or inbound-address response, not a static universal minimum.',
    category: 'operations',
    confidence: 'official',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [swapGlossaryMemosSource, swapGlossaryQueryingSource, swapGlossaryGuideSource],
    relatedHrefs: ['/network#network-diagnostics', '/deep-dives/build-query-data#quotes-inbound-addresses-and-caching'],
  },
  {
    id: slugifyFragment('Refund address'),
    term: 'Refund address',
    definition: 'An optional swap memo address for returning the inbound asset when execution refunds. It must be valid for the inbound asset chain; when omitted, or invalid in the quote flow, the refund falls back to the original sender. It selects a destination, not a refund cause or delivery proof.',
    category: 'operations',
    confidence: 'official',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [swapGlossaryGuideSource, swapGlossaryMemosSource],
    relatedHrefs: ['/deep-dives/streaming-swaps-refunds#what-to-check-first', '/network#network-diagnostics'],
  },
  {
    id: slugifyFragment('Streaming swap'),
    term: 'Streaming swap',
    definition: 'A swap split into sub-swaps to reduce slip and allow pool rebalancing. With the advanced queue, market swaps auto-stream by default, interval 0 enables rapid execution, interval 1 or more spaces sub-swaps by blocks, and quantity 0 lets the network choose; live queue controls and transaction evidence still own actual behavior.',
    category: 'operations',
    confidence: 'official',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [streamingSwapsSource, swapGlossaryMemosSource, swapGlossaryGuideSource, networkHaltsSource],
    relatedHrefs: ['/deep-dives/streaming-swaps-refunds', '/network#network-diagnostics'],
  },
  {
    id: slugifyFragment('liquidity_tolerance_bps'),
    term: 'liquidity_tolerance_bps',
    definition: 'A quote parameter that converts the expected output into a fee-aware minimum output in the generated memo. The swap reverts or refunds when output falls beyond that basis-point tolerance; unlike tolerance_bps, it accounts for swap and outbound fees, but it is not route or settlement proof.',
    category: 'economics',
    confidence: 'official',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [swapGlossaryGuideSource, swapGlossaryMemosSource],
    relatedHrefs: ['/deep-dives/streaming-swaps-refunds#memos-limits-and-refund-addresses', '/deep-dives/clp#evidence-ladder'],
  },
  {
    id: slugifyFragment('Outbound fee'),
    term: 'Outbound fee',
    definition: 'A fee component associated with the outbound transaction and chain gas. Exact values are live protocol data, not static wiki constants.',
    category: 'economics',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [feesSource],
    relatedHrefs: ['/economics', '/stats#stats-look-here-first'],
  },
  {
    id: slugifyFragment('Affiliate fee'),
    term: 'Affiliate fee',
    definition: 'An optional memo-defined interface or affiliate fee, usually expressed in basis points. It is distinct from protocol liquidity and gas-related fees.',
    category: 'economics',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [feesSource],
    relatedHrefs: ['/economics', '/dynamic-fees#dynamic-fees-live'],
  },
  {
    id: slugifyFragment('THORName'),
    term: 'THORName',
    definition: 'A THORChain L1 vanity-name and alias record with an owner, expiry, chain aliases, and optional preferred asset for affiliate-fee payouts. It can support affiliate tracking and fee collection, but it does not by itself prove current dynamic-fee attribution, route quality, or interface safety.',
    category: 'developer',
    confidence: 'official',
    reviewedAt: '2026-07-09',
    nextReviewDue: '2026-08-09',
    sources: [thornameGuideSource],
    relatedHrefs: ['/docs#developer-integration', '/dynamic-fees#dynamic-fees-live', '/glossary#term-affiliate-fee'],
  },
  {
    id: slugifyFragment('Dynamic L1 fee'),
    term: 'Dynamic L1 fee',
    definition: 'ADR-026 experiment terminology for per-thorname, per-pair L1 minimum slip floors adjusted by TOR-denominated fee evidence. Live state is current-only THORNode evidence.',
    category: 'economics',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [adr026DynamicFeesSource],
    relatedHrefs: ['/dynamic-fees#dynamic-fees-live', '/docs#dynamic-fee-experiment'],
  },
  {
    id: slugifyFragment('Protocol-owned liquidity'),
    term: 'Protocol-owned liquidity',
    definition: 'Liquidity controlled by the protocol rather than ordinary external LPs. Balances and PnL come from current accounting, while enabled pool scope comes from live `POL-<Asset>` Mimir keys; neither should be inferred from a fixed documentation count.',
    category: 'economics',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [runePoolDocsSource, runePoolDevSource, runePoolEndpointSource],
    relatedHrefs: ['/economics#runepool-pol-live', '/deep-dives/runepool-pol#accounting-checks', '/stats#stats-look-here-first'],
  },
  {
    id: slugifyFragment('RUNEPool'),
    term: 'RUNEPool',
    definition: 'A RUNE-only participation mechanism with aggregate exposure to POL-enabled pools. Current value, potentially negative PnL/current-deposit fields, POL scope, and deposit or withdrawal availability need same-provider, height-pinned THORNode and Mimir evidence.',
    category: 'economics',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [runePoolDocsSource, runePoolDevSource, runePoolEndpointSource, networkHaltsSource],
    relatedHrefs: ['/economics#runepool-pol-live', '/deep-dives/runepool-pol#accounting-checks', '/network#network-diagnostics'],
  },
  {
    id: slugifyFragment('Secured asset'),
    term: 'Secured asset',
    definition: 'A Cosmos bank asset minted from deposited L1 assets, representing shares of deposited-asset depth and usable by accounts, IBC, and CosmWasm. The high-level and developer docs differ on whether this replaces Trade Assets or Trade Accounts; neither wording proves module removal, conversion, or current availability.',
    category: 'protocol',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [securedAssetsSource, securedAssetsDevSource, assetNotationSource, networkHaltsSource],
    relatedHrefs: ['/deep-dives/app-layer', '/economics', '/network#network-diagnostics'],
  },
  {
    id: slugifyFragment('Trade asset'),
    term: 'Trade asset',
    definition: 'A 1:1 L1-backed balance held outside liquidity pools in THORChain\'s trade-account module for fast trading flows. Trade assets use `CHAIN~ASSET` notation; enablement and route availability are live controls.',
    category: 'protocol',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [tradeAssetsSource, assetNotationSource, networkHaltsSource],
    relatedHrefs: ['/deep-dives/app-layer', '/economics', '/network#network-diagnostics'],
  },
  {
    id: slugifyFragment('Synthetic asset'),
    term: 'Synthetic asset',
    definition: 'A Cosmos bank asset type, often shortened to synth, denoted with `CHAIN/ASSET` and distinct from secured (`CHAIN-ASSET`) and trade (`CHAIN~ASSET`) notation. Synthetics were part of historical Savers mechanics; notation and documented memo handlers do not prove that minting, swapping, or Savers actions are currently available.',
    category: 'history',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [assetNotationSource, archivedSaversSource, networkHaltsSource],
    relatedHrefs: ['/deep-dives/savers', '/docs#developer-integration', '/network#network-diagnostics'],
  },
  {
    id: slugifyFragment('App Layer'),
    term: 'App Layer',
    definition: 'THORChain application-layer functionality built around CosmWasm contracts, Mimir-governed deployment permissioning, and scoped deployer, checksum, and contract controls.',
    category: 'developer',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [appLayerSource, cosmwasmSource, constantsMimirSource, networkHaltsSource],
    relatedHrefs: ['/deep-dives/app-layer', '/protocol', '/network#network-diagnostics'],
  },
  {
    id: slugifyFragment('CosmWasm'),
    term: 'CosmWasm',
    definition: 'Smart-contract technology used for THORChain app-layer functionality. Current deployer, checksum, contract, or global halt state must be read from live controls.',
    category: 'developer',
    confidence: 'curated',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [cosmwasmSource, networkHaltsSource],
    relatedHrefs: ['/deep-dives/app-layer', '/protocol', '/docs#official-protocol-documentation'],
  },
  {
    id: slugifyFragment('Savers'),
    term: 'Savers',
    definition: 'A permanently deprecated THORFi feature that used single-sided synthetic accounting. Official archived docs date deprecation to 2025-01-04; retained mechanics and memo references are historical evidence, not current deposit, yield, or redemption instructions.',
    category: 'history',
    confidence: 'official',
    reviewedAt: '2026-07-14',
    nextReviewDue: '2026-08-14',
    sources: [archivedSaversSource, archivedLendingSource, tcyGuideSource],
    relatedHrefs: ['/tcy', '/deep-dives/savers'],
  },
  {
    id: slugifyFragment('TCY'),
    term: 'TCY',
    definition: 'A recovery-token framing associated with the THORFi unwind. Official sources describe 1 TCY per $1 of defaulted THORFi debt and warn that full recovery is market dependent, so current claim, staking, and value claims need fresh evidence.',
    category: 'history',
    confidence: 'official',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [tokenomicsSource, tcyGuideSource, archivedSource],
    relatedHrefs: ['/tcy', '/deep-dives/tcy-recovery-timeline', '/governance#current-recovery'],
  },
  {
    id: slugifyFragment('DKLS'),
    term: 'DKLS',
    definition: 'A threshold-signature scheme family in THORChain\'s post-exploit migration plan. The June 2026 post-restart update still describes chain-by-chain DKLS/FROST migration as future work, not completed current implementation.',
    category: 'history',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [exploitReport2Source, postRestartSecuritySource],
    relatedHrefs: ['/deep-dives/tss', '/governance#current-recovery'],
  },
  {
    id: slugifyFragment('Schnorr'),
    term: 'Schnorr',
    definition: 'A signature construction related to the FROST direction discussed after the GG20 exploit. Official post-restart reporting describes evaluation and future chain-by-chain migration, not proof that current vault signing has moved to Schnorr/FROST.',
    category: 'history',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [exploitReport2Source, postRestartSecuritySource],
    relatedHrefs: ['/deep-dives/tss', '/governance#current-recovery'],
  },
  {
    id: slugifyFragment('GG20'),
    term: 'GG20',
    definition: 'The threshold-signature implementation family used in the May 2026 exploit path. v3.19.1 patched the incident class, but official post-restart reporting still treats migration away from GG20 as future work; neither fact is present-day vault-safety proof.',
    category: 'history',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [exploitReport2Source, protocolUpgradeV319Source, postRestartSecuritySource],
    relatedHrefs: ['/deep-dives/tss', '/governance#current-recovery'],
  },
  {
    id: slugifyFragment('Paillier'),
    term: 'Paillier',
    definition: 'A cryptographic component used in the GG20/ECDSA signing path discussed in the 2026 exploit report. The report ties malformed Paillier key material to the attack, so Paillier claims should stay attached to dated incident sources.',
    category: 'history',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [exploitReport2Source],
    relatedHrefs: ['/deep-dives/tss', '/governance#current-recovery'],
  },
  {
    id: slugifyFragment('MTA'),
    term: 'MTA',
    definition: 'Multiplicative-to-additive signing-round terminology from GG20/ECDSA threshold signing. THORChain Exploit Report 2 says repeated failed MTA rounds leaked enough key-share material for the attacker to reproduce one vault key.',
    category: 'history',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [exploitReport2Source],
    relatedHrefs: ['/deep-dives/tss', '/governance#current-recovery'],
  },
  {
    id: slugifyFragment('Multi-prime modulus'),
    term: 'Multi-prime modulus',
    definition: 'A Paillier-key property discussed in the official exploit report. Use it as incident-root-cause vocabulary, not as a standalone explanation of current THORChain cryptography.',
    category: 'history',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [exploitReport2Source],
    relatedHrefs: ['/deep-dives/tss', '/governance#current-recovery'],
  },
  {
    id: slugifyFragment('Key-sign failures'),
    term: 'Key-sign failures',
    definition: 'Validator signing failures or failed signing rounds. Exploit Report 2 says many deliberate MTA failures looked like ordinary node flakiness in isolation, so key-sign failure claims need dated incident context and current monitoring evidence.',
    category: 'operations',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [exploitReport2Source, protocolUpgradeV319Source, postRestartSecuritySource],
    relatedHrefs: ['/deep-dives/tss', '/network#network-diagnostics', '/governance#current-recovery'],
  },
  {
    id: slugifyFragment('Compromised vault'),
    term: 'Compromised vault',
    definition: 'A vault treated as unsafe or excluded after key-compromise evidence. Post-exploit upgrade notes discuss compromised-vault exclusion, but current vault status still needs live protocol and incident-source checks.',
    category: 'operations',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [exploitReport2Source, protocolUpgradeV319Source, adr028ExploitConciliationSource],
    relatedHrefs: ['/deep-dives/tss', '/network#network-diagnostics', '/governance#current-recovery'],
  },
  {
    id: slugifyFragment('KeyVerify'),
    term: 'KeyVerify',
    definition: 'A temporary recovery check introduced around the v3.19 restart to confirm validators\' security keys before trading resumed. It is dated recovery evidence, not a standing guarantee of current vault or signing safety.',
    category: 'history',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [protocolUpgradeV319Source, exploitReport2Source],
    relatedHrefs: ['/deep-dives/tss', '/governance#current-recovery'],
  },
  {
    id: slugifyFragment('TSS'),
    term: 'TSS',
    definition: 'Threshold Signature Scheme. Validators jointly sign vault transactions without a single node intending to hold the complete private key; current scheme and safety claims require dated incident, release, and live evidence.',
    category: 'protocol',
    confidence: 'curated',
    reviewedAt: '2026-07-13',
    nextReviewDue: '2026-08-13',
    sources: [bifrostTssVaultsSource, exploitReport2Source, postRestartSecuritySource],
    relatedHrefs: ['/deep-dives/tss'],
  },
];
