import { test, expect } from '@playwright/test';

test.describe('THORChain Wiki Governance Smoke Tests', () => {
  test('governance page shows incidents and milestones', async ({ page }) => {
    await page.goto('/governance');
    await expect(page.getByRole('heading', { name: /Governance & History/i })).toBeVisible();
    await expect(page.locator('#governance-claim-checks')).toBeVisible();
    await expect(page.getByText('Claim checks by type', { exact: true })).toBeVisible();
    await page.locator('#governance-claim-checks').locator('details').locator('summary').click();
    await expect(page.getByText(/Operational Mimir claim/i).first()).toBeVisible();
    await expect(page.getByText(/ADR or proposal status/i).first()).toBeVisible();
    await expect(page.getByText(/Incident root-cause claim/i).first()).toBeVisible();
    await expect(page.getByText(/Recovery or solvency claim/i).first()).toBeVisible();
    await expect(page.getByText(/Community sentiment claim/i).first()).toBeVisible();
    await expect(page.getByRole('link', { name: /Check live diagnostics/i })).toHaveAttribute('href', '/network#network-diagnostics');
    await expect(page.getByRole('link', { name: /Read security path/i })).toHaveAttribute('href', '/deep-dives#deep-dive-path-network-security');
    await expect(page.getByRole('link', { name: /Review recovery tracker/i })).toHaveAttribute('href', '#current-recovery');
    await expect(page.getByText(/Do not present Discord chatter as canonical protocol proof/i)).toBeVisible();
    await expect(page.getByRole('heading', { name: /Current Incident & Recovery Tracker/i })).toBeVisible();
    await expect(page.locator('#current-recovery').getByText('Show summary and claim-check detail')).toBeVisible();
    // Recovery tracker details is now open by default — content is already visible
    await expect(page.getByText(/full recovery is not guaranteed/i)).toBeVisible();
    await expect(page.locator('#current-recovery').getByRole('heading', { name: /ADR-028 Recovery Path/i })).toBeVisible();
    await expect(page.locator('#current-recovery').getByText('Tracked records')).toBeVisible();
    await expect(page.locator('#current-recovery').getByText('Record + live check')).toBeVisible();
    await expect(page.locator('#current-recovery').getByText(/Use This For/i).first()).toBeVisible();
    await expect(page.locator('#current-recovery').getByText(/Verify Next/i).first()).toBeVisible();
    await expect(page.locator('#current-recovery').getByText(/Network diagnostics for current halts, signing, route limits/i)).toBeVisible();
    await expect(page.locator('#current-recovery').getByText(/immutable v3.19.0 ADR before describing its reserve, Saver, treasury, or stuck-swap allocation waterfall/i)).toBeVisible();
    await expect(page.locator('#current-recovery').getByText(/ADR-028 acceptance proves the conciliation decision and migration design, not that every loss was restored/i)).toBeVisible();
    await expect(page.locator('#current-recovery').locator('a[href="/governance#incident-gg20-vault-exploit-2026"]').first()).toBeVisible();
    await expect(page.locator('#current-recovery').getByRole('link', { name: /Open governance record/i })).toHaveAttribute('href', '/governance#governance-adr-028-recovery');
    await expect(page.locator('#current-recovery').getByRole('link', { name: /Check current diagnostics/i }).first()).toHaveAttribute('href', '/network#network-diagnostics');
    await expect(page.locator('#governance-archive-map')).toBeVisible();
    await expect(page.getByRole('heading', { name: /Dated Archive Map/i })).toBeVisible();
    await expect(page.locator('#governance-archive-map').getByText(/Counts are navigation aids, not health scores/i)).toBeVisible();
    await expect(page.locator('#governance-archive-map').getByRole('link', { name: /Current recovery lane/i })).toHaveAttribute('href', '#current-recovery');
    await expect(page.locator('#governance-archive-map').getByRole('link', { name: /Governance records lane/i })).toHaveAttribute('href', '#governance-records');
    await expect(page.locator('#governance-archive-map').getByRole('link', { name: /Incident archive lane/i })).toHaveAttribute('href', '#security-incidents');
    await expect(page.locator('#governance-archive-map').getByRole('link', { name: /Research and milestones lane/i })).toHaveAttribute('href', '#protocol-milestones');
    await expect(page.locator('#governance-records').getByText(/status badge describes the record evidence posture/i)).toBeVisible();
    const adr026Record = page.locator('#governance-adr-026-dynamic-l1-fees');
    await expect(adr026Record.getByText('Record status: ADR discussion review target 2026-11-17')).toBeVisible();
    await expect(adr026Record.getByText('Review: Review due 2026-11-17')).toHaveCount(0);
    await expect(adr026Record.getByText('Review due 2026-11-17')).toBeVisible();
    const mimirRecord = page.locator('#governance-mimir-operational-halts');
    await expect(mimirRecord.getByText('Current-only control reference')).toBeVisible();
    await expect(mimirRecord.getByText('Record status: Check current THORNode Mimir state')).toBeVisible();
    await expect(page.getByRole('heading', { name: /Security Incidents/i })).toBeVisible();
    await expect(page.locator('#security-incidents')).toBeVisible();
    const incidentArchive = page.locator('#security-incidents');
    await expect(incidentArchive.getByRole('heading', { name: /Security Incidents/i })).toBeVisible();
    await expect(incidentArchive.getByRole('searchbox', { name: /Filter security incidents/i })).toBeVisible();
    await expect(incidentArchive.getByRole('button', { name: /Current tracker/i })).toBeVisible();
    await expect(incidentArchive.getByRole('button', { name: /Historical open/i })).toBeVisible();
    await expect(incidentArchive.getByRole('button', { name: /Resolved/i })).toBeVisible();
    await expect(incidentArchive.getByText(/Showing 6 of 6 incident records/i)).toBeVisible();
    await expect(page.locator('#incident-thorfi-unwind-2025').getByText('Historical open record')).toBeVisible();
    await expect(page.locator('#incident-thorfi-unwind-2025').getByText(/not promoted to current recovery status/i)).toBeVisible();
    await expect(page.locator('#incident-gg20-vault-exploit-2026').getByText('Current tracker')).toBeVisible();
    await expect(page.locator('#incident-memoless-spam-2026-08').getByText('Current tracker')).toBeVisible();
    await incidentArchive.getByRole('button', { name: /Historical open/i }).click();
    await expect(page).toHaveURL(/posture=historical-open/);
    await expect(incidentArchive.getByText('Posture: Historical open')).toBeVisible();
    await expect(incidentArchive.getByText(/Showing 2 of 6 incident records/i)).toBeVisible();
    await expect(page.locator('#incident-thorfi-unwind-2025')).toBeVisible();
    await expect(page.locator('#incident-bybit-laundering-2025')).toBeVisible();
    await expect(page.locator('#incident-gg20-vault-exploit-2026')).toHaveCount(0);
    await incidentArchive.getByRole('searchbox', { name: /Filter security incidents/i }).fill('Bybit');
    await expect(page).toHaveURL(/q=Bybit/);
    await expect(incidentArchive.getByText('Search: Bybit')).toBeVisible();
    await expect(incidentArchive.getByText(/Showing 1 of 6 incident records/i)).toBeVisible();
    await expect(page.locator('#incident-bybit-laundering-2025')).toBeVisible();
    await expect(page.locator('#incident-thorfi-unwind-2025')).toHaveCount(0);
    await incidentArchive.getByRole('button', { name: /Reset filters/i }).click();
    await expect(page).toHaveURL(/\/governance$/);
    await expect(incidentArchive.getByText(/Showing 6 of 6 incident records/i)).toBeVisible();
    await expect(page.locator('#governance-research').getByText(/Dated analysis and roadmap context/i)).toBeVisible();

    await page.goto('/governance?posture=current&q=GG20');
    const hydratedIncidentArchive = page.locator('#security-incidents');
    await expect(hydratedIncidentArchive.getByText('Posture: Current tracker')).toBeVisible();
    await expect(hydratedIncidentArchive.getByText('Search: GG20')).toBeVisible();
    await expect(hydratedIncidentArchive.getByText(/Showing 1 of 6 incident records/i)).toBeVisible();
    await expect(page.locator('#incident-gg20-vault-exploit-2026')).toBeVisible();
    await expect(page.locator('#incident-thorfi-unwind-2025')).toHaveCount(0);

    await page.evaluate(() => {
      window.history.pushState(window.history.state, '', '/governance?posture=historical-open&q=Bybit');
      window.dispatchEvent(new PopStateEvent('popstate', { state: window.history.state }));
    });
    await expect(hydratedIncidentArchive.getByRole('searchbox', { name: /Filter security incidents/i })).toHaveValue('Bybit');
    await expect(hydratedIncidentArchive.getByText('Posture: Historical open')).toBeVisible();
    await expect(hydratedIncidentArchive.getByText('Search: Bybit')).toBeVisible();
    await expect(page.locator('#incident-bybit-laundering-2025')).toBeVisible();
    await expect(page.locator('#incident-gg20-vault-exploit-2026')).toHaveCount(0);
  });
});
