import { test, expect } from '@playwright/test';

test.describe('THORChain Wiki Home Smoke Tests', () => {
  test('home page loads and shows key sections @docker-smoke', async ({ page, isMobile }) => {
    await page.goto('/');
    await expect(page.getByRole('heading', { name: /THORChain Wiki/i })).toBeVisible();
    await expect(page.getByRole('link', { name: /Skip to content/i })).toHaveAttribute('href', '#main');
    await expect(page.getByText(/Community-maintained encyclopedia/i).first()).toBeVisible();
    await expect(page.locator('#home-source-router')).toBeVisible();
    await expect(page.getByRole('heading', { name: /Start With The Claim/i })).toBeVisible();
    await expect(page.locator('#home-source-router').getByRole('link', { name: /Live operations/i })).toHaveAttribute('href', '/network#network-diagnostics');
    await expect(page.locator('#home-source-router').getByRole('link', { name: /Metrics/i })).toHaveAttribute('href', '/stats#stats-look-here-first');
    await expect(page.locator('#home-source-router').getByRole('link', { name: /Design or history/i })).toHaveAttribute('href', '/deep-dives#deep-dive-reader-paths');
    await expect(page.locator('#home-source-router').getByRole('link', { name: /Official sources/i })).toHaveAttribute('href', '/docs#source-map-chooser');
    const homePosture = page.getByRole('region', { name: 'Source and freshness' });
    await expect(homePosture).toBeVisible();
    await expect(page.getByRole('heading', { name: /Live Operations Snapshot/i })).toBeVisible();
    await expect(page.locator('section[aria-labelledby="home-live-status-heading"]').getByRole('link', { name: 'Open diagnostics', exact: true })).toHaveAttribute('href', '/network#network-diagnostics');
    await expect(page.getByRole('heading', { name: /Check The Right Thing First/i })).toBeVisible();
    await expect(page.getByRole('link', { name: /Can I use THORChain now/i })).toHaveAttribute('href', '/network#check-a-route');
    await expect(page.getByRole('link', { name: /Which number matters/i })).toHaveAttribute('href', '/stats#stats-look-here-first');
    await expect(page.getByRole('link', { name: /Is ADR-026 relevant/i })).toHaveAttribute('href', '/dynamic-fees#dynamic-fees-live');
    await expect(page.getByRole('link', { name: /Is this a RUNE claim/i })).toHaveAttribute('href', '/rune#rune-number-router');
    await expect(page.getByRole('link', { name: /Is this RUNEPool or POL/i })).toHaveAttribute('href', '/economics#runepool-pol-live');
    await expect(page.getByRole('link', { name: /Can I claim or stake TCY/i })).toHaveAttribute('href', '/tcy#tcy-current-controls');
    await expect(page.getByRole('link', { name: /Is this history or recovery/i })).toHaveAttribute('href', '/governance#governance-claim-checks');
    await expect(page.getByRole('link', { name: /Which interface should I inspect/i })).toHaveAttribute('href', '/ecosystem#interface-use-checklist');
    await expect(page.getByRole('link', { name: 'Browse guided answers', exact: true })).toHaveAttribute('href', '/search#search-guided-answers');
    await expect(page.getByRole('heading', { name: /Learn in Sequence/i })).toBeVisible();
    await expect(page.getByRole('link', { name: /Network Security/i })).toHaveAttribute('href', '/deep-dives#deep-dive-path-network-security');
    await expect(page.getByText(/Verify before claiming: Current signing/i)).toBeVisible();
    await expect(page.getByText('Midgard Pool Rows')).toBeVisible();
    await expect(page.getByText(/Counts Midgard .* rows/i)).toBeVisible();
    await expect(page.getByText(/not proof that a route will quote or settle/i)).toBeVisible();
    await expect(page.getByText('Available Pools')).toHaveCount(0);
    const networkStatus = page.getByRole('status').first();
    await expect(networkStatus).toBeVisible();
    await expect(networkStatus.getByText(/live sources|checking live network status|network status unavailable|network status unknown|ordinary swaps|some routes limited|no global swap halt|source degraded|source review/i).first()).toBeVisible();
    await expect(networkStatus.getByText(/swaps appear/i)).toHaveCount(0);
    await expect(page.getByText(/Pointer list, not endorsement/i)).toBeVisible();
    await expect(page.getByText('Catalog listed', { exact: true }).first()).toBeVisible();
    await expect(page.getByText(/Verify live quote, route, fees, recipient/i).first()).toBeVisible();
    await expect(page.getByText(/Needs source review/i).first()).toBeVisible();
    await expect(page.getByText(/Confirm the direct source is reachable/i).first()).toBeVisible();
    await expect(page.getByText(/Verify package versions, API behavior/i).first()).toBeVisible();
    await expect(page.getByRole('link', { name: /THORChain Swap/i })).toHaveAttribute('href', '/ecosystem#ecosystem-thorchain-swap');
    await expect(page.getByRole('link', { name: /Open interface checklist/i })).toHaveAttribute('href', '/ecosystem#interface-use-checklist');
    await expect(page.getByText(/Dated analysis context, not live protocol proof/i)).toBeVisible();
    await expect(page.getByText(/Not live protocol proof/i).first()).toBeVisible();
    await expect(page.getByText(/External sources answer different questions/i)).toBeVisible();
    const footer = page.locator('footer');
    await expect(footer.getByText('Verify First', { exact: true })).toBeVisible();
    await expect(footer.getByRole('link', { name: /Source map/i })).toHaveAttribute('href', '/docs#source-map-chooser');
    await expect(footer.getByRole('link', { name: /Network diagnostics/i })).toHaveAttribute('href', '/network#network-diagnostics');
    await expect(footer.getByRole('link', { name: /^Interface checklist\b/i })).toHaveAttribute('href', '/ecosystem#interface-use-checklist');
    await expect(footer.getByRole('link', { name: /Guided answers/i })).toHaveAttribute('href', '/search#search-guided-answers');
    await expect(footer.getByText(/Match source to claim/i)).toBeVisible();
    await expect(footer.getByText('Official Sources/APIs', { exact: true })).toBeVisible();
    await expect(footer.getByText('Third-Party Surfaces', { exact: true })).toBeVisible();
    await expect(footer.getByRole('link', { name: /THORChain Docs/i })).toBeVisible();
    await expect(footer.getByText(/Official protocol documentation/i)).toBeVisible();
    await expect(footer.getByText('Gateway API', { exact: true })).toBeVisible();
    await expect(footer.getByRole('link', { name: /Review data-source guide/i })).toHaveAttribute('href', '/deep-dives/midgard-thornode-data');
    await expect(footer.getByText('RuneScan', { exact: true })).toBeVisible();
    await expect(footer.getByRole('link', { name: /Review explorer posture/i })).toHaveAttribute('href', '/docs#external-analytics-and-explorers');
    await expect(footer.getByText('THORSwap', { exact: true })).toBeVisible();
    await expect(footer.getByRole('link', { name: /Review interface checklist/i })).toHaveAttribute('href', '/ecosystem#interface-use-checklist');
    await expect(footer.getByText(/Interface surface; verify route, recipient, fees/i)).toBeVisible();
    await expect(footer.getByRole('link', { name: /Open Gateway API externally/i })).toHaveAttribute('href', 'https://gateway.liquify.com/chain/thorchain_midgard/v2');
    await expect(footer.getByRole('link', { name: /Open RuneScan externally/i })).toHaveAttribute('href', 'https://runescan.io');
    await expect(footer.getByRole('link', { name: /Open THORSwap externally/i })).toHaveAttribute('href', 'https://app.thorswap.finance');
    await expect(footer.getByText('Open Gateway API', { exact: true })).toBeVisible();
    await expect(footer.getByText('Open RuneScan', { exact: true })).toBeVisible();
    await expect(footer.getByText('Open THORSwap', { exact: true })).toBeVisible();
    await expect(footer.getByText('Open external', { exact: true })).toHaveCount(0);
    await expect(footer.getByText(/Page and record review dates are authoritative/i)).toBeVisible();
    await expect(footer.getByText(/base static-catalog baseline/i)).toBeVisible();
    if (!isMobile) {
      await page.getByRole('button', { name: /Guides/i }).click();
      const guides = page.getByRole('navigation', { name: /Guide links/i });
      await expect(guides.getByText(/Reader Paths/i)).toBeVisible();
      await expect(guides.getByText(/Common Tasks/i)).toBeVisible();
      await expect(guides.getByText('Use Now', { exact: true })).toBeVisible();
      await expect(guides.getByText('Learn & Explain', { exact: true })).toBeVisible();
      await expect(guides.getByText('Build & Inspect', { exact: true })).toBeVisible();
      await expect(guides.getByText('Trust & Recovery', { exact: true })).toBeVisible();
      await expect(guides.getByRole('link', { name: /New to THORChain/i })).toHaveAttribute('href', '/deep-dives#deep-dive-path-new-to-thorchain');
      await expect(guides.getByRole('link', { name: /Can I swap right now/i })).toHaveAttribute('href', '/network#check-a-route');
      await expect(guides.getByRole('link', { name: /Learning paths/i })).toHaveAttribute('href', '/deep-dives#deep-dive-reader-paths');
      await expect(guides.getByRole('link', { name: /All guided answers/i })).toHaveAttribute('href', '/search#search-guided-answers');
      await expect(guides.locator('a[href="/stats#stats-look-here-first"]')).toBeVisible();
      await expect(guides.locator('a[href="/deep-dives/build-query-data#query-plan"]').first()).toBeVisible();
      await expect(guides.getByRole('link', { name: /RUNE and tokenomics claims/i })).toHaveAttribute('href', '/rune#rune-number-router');
      await page.keyboard.press('Escape');
      await expect(page.locator('#desktop-guides-panel')).toHaveCount(0);
    }
  });
});
